artifact_location: file:C:/Users/karti/Desktop/Gesture_Detection/runs/mlflow/508391912831682780
creation_time: 1779894888440
experiment_id: '508391912831682780'
last_update_time: 1779894888440
lifecycle_stage: active
name: /Shared/Ultralytics
workspace: default
